language: go

go:
- 1.7

before_install:
- go get -u -v github.com/golang/lint/golint
- go get -u -v code.google.com/p/go.tools/cmd/vet

install:
- go get -u ./...

script:
- golint ./...
- go vet ./...
- go test -cover -v ./...
