---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial

inputs:
- name: console
- name: version

outputs:
- name: release-notes

run:
  path: console/ci/scripts/build-release-notes.sh
