---
resources:
- name: console-master
  type: git
  source:
    uri: {{.repository_git_uri}}
    branch: ci

- name: console-pr
  type: pull-request
  source:
    repo: {{.repository_user}}/{{.repository_name}}
    access_token: {{.repository_access_token}}
    private_key: |
{{.repository_private_key|indent 6}}

- name: console-github-release
  type: github-release
  source:
    user: {{.repository_user}}
    repository: {{.repository_name}}
    access_token: {{.repository_access_token}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{.slack_alert_url}}

- name: console-version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: {{.version_git_uri}}
    branch: {{.version_git_branch}}
    file: {{.version_git_file}}
    private_key: |
{{.repository_private_key|indent 6}}


jobs:
- name: console-bump-major
  serial_groups: [ version ]
  plan:
  - put: console-version
    params: { bump: major }

- name: console-bump-minor
  serial_groups: [ version ]
  plan:
  - put: console-version
    params: { bump: minor }

- name: console-bump-patch
  serial_groups: [ version ]
  plan:
  - put: console-version
    params: { bump: patch }

- name: console-bump-alpha
  serial_groups: [ version ]
  plan:
  - put: console-version
    params: { pre: alpha }

- name: console-bump-beta
  serial_groups: [ version ]
  plan:
  - put: console-version
    params: { pre: beta }

- name: console-bump-rc
  serial_groups: [ version ]
  plan:
  - put: console-version
    params: { pre: rc }

- name: test-console-master
  serial_groups: [ version ]
  plan:
  - aggregate:
    - get: console-master
      trigger: true
    - get: console-version
  - task: test
    file: console-master/ci/tasks/test.yml
    input_mapping: { console: console-master }
  - put: console-version
    params: { file: console-version/version }
  on_success:
    put: slack-alert
    params:
      channel: "#{{.slack_alert_channel}}"
      text: >
        <!here|here> Tests for <{{.repository_http_uri}}|{{.repository_fqn}}> succeeded. View the
        build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID
  on_failure:
    put: slack-alert
    params:
      channel: "#{{.slack_alert_channel}}"
      text: >
        <!here|here> Tests for <{{.repository_http_uri}}|{{.repository_fqn}}> failed. View the
        build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID

- name: test-console-pr
  plan:
  - get: console-pr
    trigger: true
    version: every
  - put: console-pr
    params: { path: console-pr, status: pending }
  - task: test
    file: console-pr/ci/tasks/test.yml
    input_mapping: { console: console-pr }
  on_success:
    put: console-pr
    params: { path: console-pr, status: success }
  on_failure:
    put: console-pr
    params: { path: console-pr, status: failure }

- name: github-release
  plan:
  - aggregate:
    - get: console-master
      passed: [ test-console-master ]
    - get: console-version
      passed: [ test-console-master ]
  - task: build-release-notes
    file: console-master/ci/tasks/build-release-notes.yml
    input_mapping: { console: console-master, version: console-version }
  - put: console-github-release
    params:
      name: console-version/version
      tag: console-version/version
      tag_prefix: v
      body: release-notes/notes.md

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
