---
resources:
- name: console
  type: git
  source:
    uri: {{.repository_git_url}}
    branch: ci

- name: slack-alert
  type: slack-notification
  source:
    url: {{.slack_alert_url}}

- name: version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: {{.version_git_uri}}
    branch: {{.version_git_branch}}
    file: {{.version_git_file}}
    private_key: {{.version_git_private_key}}


jobs:
- name: test
  plan:
  - get: console
    trigger: true
  - task: test
    file: console/ci/tasks/test.yml
    on_success:
      put: slack-alert
      params:
        channel: "#{{.slack_alert_channel}}"
        text: >
          <!here|here> Tests for <{{.repository_http_url}}|{{.repository_name}}> succeeded. View the
          build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID
    on_failure:
      put: slack-alert
      params:
        channel: "#{{.slack_alert_channel}}"
        text: >
          <!here|here> Tests for <{{.repository_http_url}}|{{.repository_name}}> failed. View the
          build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID

- name: bump-major
  plan:
  - get: version
    params:
      bump: major
      pre: rc

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
