---
resources:
- name: console
  type: git
  source:
    uri: {{.repository_git_uri}}
    branch: ci

- name: console-pr
  type: pull-request
  source:
    repo: {{.repository_user}}/{{.repository_name}}
    access_token: {{.repository_access_token}}
    private_key: |
{{.repository_private_key|indent 6}}

- name: github-release
  type: github-release
  source:
    user: {{.repository_user}}
    repository: {{.repository_name}}
    access_token: {{.repository_access_token}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{.slack_alert_url}}

- name: version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: {{.version_git_uri}}
    branch: {{.version_git_branch}}
    file: {{.version_git_file}}
    private_key: |
{{.repository_private_key|indent 6}}


jobs:
- name: major
  serial_groups: [ version ]
  plan:
  - put: version
    params: { bump: major }

- name: minor
  serial_groups: [ version ]
  plan:
  - put: version
    params: { bump: minor }

- name: patch
  serial_groups: [ version ]
  plan:
  - put: version
    params: { bump: patch }

- name: alpha
  serial_groups: [ version ]
  plan:
  - put: version
    params: { pre: alpha }

- name: beta
  serial_groups: [ version ]
  plan:
  - put: version
    params: { pre: beta }

- name: rc
  serial_groups: [ version ]
  plan:
  - put: version
    params: { pre: rc }

- name: test
  serial_groups: [ version ]
  plan:
  - aggregate:
    - get: console
      trigger: true
    - get: version
  - task: test
    file: console/ci/tasks/test.yml
    on_success:
      put: slack-alert
      params:
        channel: "#{{.slack_alert_channel}}"
        text: >
          <!here|here> Tests for <{{.repository_http_uri}}|{{.repository_fqn}}> succeeded. View the
          build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID
    on_failure:
      put: slack-alert
      params:
        channel: "#{{.slack_alert_channel}}"
        text: >
          <!here|here> Tests for <{{.repository_http_uri}}|{{.repository_fqn}}> failed. View the
          build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID
  - put: version
    params: { file: version/version }

- name: test-pr
  plan:
  - get: console-pr
    trigger: true
    version: every
  - put: console-pr
    params: { path: console-pr, status: pending }
  - task: test
    file: console-pr/ci/tasks/test.yml
    input_mapping: { console: console-pr }
    on_success:
      put: console-pr
      params: { path: console-pr, status: success }
    on_failure:
      put: console-pr
      params: { path: console-pr, status: failure }

- name: github-release
  plan:
  - aggregate:
    - get: console
      passed: [ test ]
    - get: version
      passed: [ test ]
  - task: build-release-notes
    file: console/ci/tasks/build-release-notes.yml
  - put: github-release
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      body: release-notes/notes.md

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
