---
resources:
- name: console
  type: git
  source:
    uri: {{.repository_git_url}}
    branch: ci

- name: slack-alert
  type: slack-notification
  source:
    url: {{.slack_alert_url}}


jobs:
- name: test
  plan:
  - get: console
    trigger: true
  - task: test
    file: console/ci/tasks/test.yml
    on_success:
      put: slack-alert
      params:
        channel: "#{{.slack_alert_channel}}"
        text: >
          <!here|here> Tests for <{{.repository_http_url}}|{{.repository_name}}> succeeded. View the
          build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID
    on_failure:
      put: slack-alert
      params:
        channel: "#{{.slack_alert_channel}}"
        text: >
          <!here|here> Tests for <{{.repository_http_url}}|{{.repository_name}}> failed. View the
          build log at $ATC_EXTERNAL_URL/builds/$BUILD_ID


resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
