---
resources:
- name: console
  type: git
  source:
    uri: https://github.com/eidolon/console.git
    branch: master

jobs:
- name: test
  plan:
  - get: console
    trigger: true
  - task: test
    file: console/ci/test.yml
